version: '3.8'
services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=fisa'
      - 'MYSQL_USER=newuser'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  
  newmysqldb:
    container_name: newmysqldb
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=newfisa'  # 새로운 데이터베이스 이름
      - 'MYSQL_USER=newuser'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'
    volumes:
      - 'new_mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
  new_mysql_data:
